# Generated by Django 4.2 on 2024-09-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funveh', '0002_alter_vehiculo_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
    ]
