# Generated by Django 4.2 on 2024-09-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funveh', '0003_funcionario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='aprobacion_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
