# Generated by Django 4.2 on 2024-10-11 21:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funveh', '0004_funcionario_aprobacion_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funveh.vehiculo')),
            ],
        ),
    ]
