# Generated by Django 4.2 on 2024-10-11 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funveh', '0005_movimientovehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientovehiculo',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='movimientovehiculo',
            name='fecha_entrada',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='movimientovehiculo',
            name='fecha_salida',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='movimientovehiculo',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funveh.funcionario'),
        ),
        migrations.AddField(
            model_name='movimientovehiculo',
            name='hora_entrada',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='movimientovehiculo',
            name='hora_salida',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='movimientovehiculo',
            name='tipo_movimiento',
            field=models.CharField(max_length=50),
        ),
    ]
