# Generated by Django 4.2 on 2024-10-11 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funveh', '0006_remove_movimientovehiculo_fecha_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientovehiculo',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='movimientovehiculo',
            name='hora_salida',
        ),
        migrations.AlterField(
            model_name='movimientovehiculo',
            name='fecha_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientovehiculo',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientovehiculo',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funveh.funcionario'),
        ),
    ]
