# Generated by Django 4.2 on 2024-10-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funveh', '0008_remove_movimientovehiculo_funcionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='area',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
    ]
