# Generated by Django 4.2 on 2024-10-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funveh', '0010_area_cargo_alter_funcionario_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='area',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
