# Generated by Django 4.2 on 2024-10-17 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funveh', '0011_alter_funcionario_area_alter_funcionario_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='area',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
    ]
