# Generated by Django 4.2 on 2024-10-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funveh', '0013_area_cargo_remove_vehiculo_tipovehiculo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='aprobacion_id',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='fecha_aprobacion',
        ),
    ]
