# Generated by Django 4.2 on 2024-10-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funveh', '0015_aprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
